version: '3.8'
services:
  boot-node:
    build:
      context: .
      args: ["VM_DEBUG=true"]
    command: ["juno", "--http", "--p2p", "--p2p-bootnode", "--p2p-addr", "/ip4/0.0.0.0/tcp/7777"]
    ports:
      - "6060:6060"
    deploy:
      resources:
        limits:
          cpus: '1'

  node:
    build:
      context: .
      args: ["VM_DEBUG=true"]
    command: ["juno", "--http", "--p2p", "--p2p-boot-peers", "/ip4/boot-node/tcp/7777"]
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
