version: '3.8'
# first, run "docker build -t juno:latest"
services:
  boot-node:
    image: juno:latest
    networks:
      p2p-network:
        ipv4_address: 192.168.10.10
    command: ["juno", "--http", "--p2p", "--p2p-bootnode", "--p2p-addr", "/ip4/0.0.0.0/tcp/7777"]
    ports:
      - "6060:6060"

  node:
    image: juno:latest
    networks: [p2p-network]
    depends_on: [boot-node]
    command: ["juno", "--http", "--p2p", "--p2p-boot-peers", "/ip4/192.168.10.10/tcp/7777/p2p/12D3KooWEbuaFLXa1NBR2k186YchYpo29pk1DPWxATiTXub7V2ad"]
    deploy:
      replicas: 2

networks:
  p2p-network:
    name: p2p-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24