[package]
name = "juno-starknet-rs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.184"
serde_json = { version = "1.0.96", features = ["raw_value"] }
blockifier = "=0.5.0-rc.1"
starknet_api = "=0.8.0"
cairo-vm = "=0.9.2"
indexmap = "2.1.0"
cached = "0.46.1"
once_cell = "1.19.0"

cairo-lang-casm = "=2.6.0-rc.0"
cairo-lang-runner = "=2.6.0-rc.0"
cairo-lang-starknet = "=2.6.0-rc.0"
cairo-lang-utils = "=2.6.0-rc.0"

[lib]
crate-type = ["staticlib"]